<?php
/**
 * BrandCrock Industryarc Theme in Magento2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GNU General Public License
 *
 * DISCLAIMER
 *
 * Do not add or edit the files if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category   BrandCrock
 * @package    BrandCrock_Industryarc
 * @copyright  Copyright (c) BrandCrock (https://www.brandcrock.com/)
 * @license    GNU General Public License
 */

$columnsLimit = $block->getColumnsLimit() ? : 0;
$menu = $block->getHtml('level-top', 'submenu', $columnsLimit);

$blockObj = $block->getLayout()->createBlock(BrandCrock\Industryarc\Block\Frontend\Block::class);
$helper = $blockObj->getHelperData();
$baseUrl = $helper->getBaseUrl();
$ishome = $helper->getIsHomePage();
$showhomelink = $helper->getThemeConfig('bcia_addhomelink');
?>

<nav class="navigation" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php if ($showhomelink) { ?>
            <li class="level0 level-top <?php if ($ishome) { ?> active <?php } ?>">
                <a class="level-top" href="<?= /* @noEscape */ $baseUrl; ?>" rel="noopener" target="_self" title="Home">
                    <span>Home</span>
                </a>
            </li>
        <?php } ?>
        <?= /* @noEscape */  $menu ?>
    </ul>
</nav>
<style>
.navigation .level0 .submenu li.parent > a::after {
    display:none;
}
</style>