<?php
/**
 * BrandCrock Industryarc Theme in Magento2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GNU General Public License
 *
 * DISCLAIMER
 *
 * Do not add or edit the files if you wish to upgrade this extension to newer
 * version in the future.
 *
 * @category   BrandCrock
 * @package    BrandCrock_Industryarc
 * @copyright  Copyright (c) BrandCrock (https://www.brandcrock.com/)
 * @license    GNU General Public License
 */

$blockObj = $block->getLayout()->createBlock(BrandCrock\Industryarc\Block\Frontend\Block::class);
$helper = $blockObj->getHelperData();
$baseUrl = $helper->getBaseUrl();

$bcia_ft_company_info  = $helper->getFooterConfig('bcia_ft_company_info');
$bcia_ft_company_desc  = $helper->getFooterConfig('bcia_ft_company_desc');
$bcia_ft_company_add  = $helper->getFooterConfig('bcia_ft_company_add');
$bcia_ft_company_email  = $helper->getFooterConfig('bcia_ft_company_email');
$bcia_ft_company_num  = $helper->getFooterConfig('bcia_ft_company_num');

$bcia_ft_company_image = $helper->getFooterImage('bcia_ft_company_image');
?>
<div class="bcia_company">
    <?php if ($bcia_ft_company_info) { ?>
    <div class="bcia_company_info">
        <div class="company_info_inner">
            <?php if ($bcia_ft_company_image) { ?>
                <img class="company_info_img" src="<?= /* @noEscape */ $bcia_ft_company_image ?>" alt="Company Logo">
            <?php } ?>
            <?php if ($bcia_ft_company_desc) { ?>
                <div class="content">
                    <?= /* @noEscape */ $bcia_ft_company_desc ?>
                </div>
            <?php } ?>
            <div class="bcia_additional_info_container">
                <ul class="bcia_additional_info">
                    <li class="bcia-info">
                        <svg width="17" height="22" viewBox="0 0 17 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M8.25 22C8.25 22 16.5 14.1818 16.5 8.25C16.5 6.06196 15.6308 3.96354 14.0836
                            2.41637C12.5365 0.869194 10.438 0 8.25 0C6.06196 0 3.96354 0.869194 2.41637
                            2.41637C0.869194 3.96354 3.26043e-08 6.06196 0 8.25C0 14.1818 8.25 22 8.25 22ZM8.25
                            12.375C7.15598 12.375 6.10677 11.9404 5.33318 11.1668C4.5596 10.3932 4.125 9.34402 4.125
                            8.25C4.125 7.15598 4.5596 6.10677 5.33318 5.33318C6.10677 4.5596 7.15598 4.125 8.25
                            4.125C9.34402 4.125 10.3932 4.5596 11.1668 5.33318C11.9404 6.10677 12.375 7.15598 12.375
                            8.25C12.375 9.34402 11.9404 10.3932 11.1668 11.1668C10.3932 11.9404 9.34402 12.375
                            8.25 12.375Z" fill="black"/>
                        </svg>
                        <span><a><?= /* @noEscape */ $bcia_ft_company_add ?></a></span>
                    </li>
                    <li class="bcia-info">
                        <svg width="30" height="22" viewBox="0 0 30 22" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M28.7776 7.26458C29.001 7.08698 29.3333 7.25313 29.3333 7.53385V19.25C29.3333
                            20.7682 28.1016 22 26.5833 22H2.75C1.23177 22 0 20.7682 0 19.25V7.53958C0 7.25313 0.326562
                            7.09271 0.555729 7.27031C1.83906 8.26719 3.54063 9.53333 9.38438 13.7786C10.5932 14.6609
                            12.6328 16.5172 14.6667 16.5057C16.712 16.5229 18.7917 14.6266 19.9547 13.7786C25.7984
                            9.53333 27.4943 8.26146 28.7776 7.26458ZM14.6667 14.6667C15.9958 14.6896 17.9094 12.9938
                            18.8719 12.2948C26.4745 6.7776 27.0531 6.29635 28.8062 4.92135C29.1385 4.66354 29.3333
                            4.2625 29.3333 3.83854V2.75C29.3333 1.23177 28.1016 0 26.5833 0H2.75C1.23177 0 0 1.23177 0
                            2.75V3.83854C0 4.2625 0.194792 4.65781 0.527083 4.92135C2.28021 6.29062 2.85885 6.7776
                            10.4615 12.2948C11.424 12.9938 13.3375 14.6896 14.6667 14.6667Z" fill="black"/>
                        </svg>
                        <span>
                            <a id="mailto" href="mailto:<?= /* @noEscape */ $bcia_ft_company_email ?>" rel="noopener"
                                target="_blank" title="<?= /* @noEscape */ $bcia_ft_company_email ?>">
                                <?= /* @noEscape */ $bcia_ft_company_email ?>
                            </a>
                        </span>
                    </li>
                    <li class="bcia-info">
                        <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M9 16C2.814 9.813 3.11 5.134 5.94 3.012l.627-.467a1.483 1.483 0 0 1 2.1.353l1.579
                            2.272a1.5 1.5 0 0 1-.25 1.99L8.476 8.474c-.38.329-.566.828-.395 1.301.316.88 1.083 2.433
                            2.897 4.246 1.814 1.814 3.366 2.581 4.246 2.898.474.17.973-.015 1.302-.396l1.314-1.518a1.5
                            1.5 0 0 1 1.99-.25l2.276 1.58a1.48 1.48 0 0 1 .354 2.096l-.47.633C19.869 21.892 15.188
                            22.187 9 16z" fill="#000000"></path>
                        </svg>
                        <span>
                            <a id="tel_no" href="tel:<?= /* @noEscape */ $bcia_ft_company_num ?>" rel="noopener"
                                target="_blank" title="<?= /* @noEscape */ $bcia_ft_company_num ?>">
                                <?= /* @noEscape */ $bcia_ft_company_num ?>
                            </a>
                        </span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <?php } ?>
    <div class="footer_links">
        <div class="title">About</div>
        <ul class="footer links">
            <li class="nav item">
                <a href="<?= /* @noEscape */ $baseUrl; ?>privacy-policy-cookie-restriction-mode/">
                    Privacy and Cookie Policy
                </a>
            </li>
            <li class="nav item">
                <a href="<?= /* @noEscape */ $baseUrl; ?>search/term/popular/">Search Terms</a>
            </li>
            <li class="nav item">
                <a href="<?= /* @noEscape */ $baseUrl; ?>catalogsearch/advanced/" data-action="advanced-search">
                    Advanced Search
                </a>
            </li>
            <li class="nav item">
                <a href="<?= /* @noEscape */ $baseUrl; ?>sales/guest/form/">Orders and Returns</a>
            </li>
            <li class="nav item">
                <a href="<?= /* @noEscape */ $baseUrl; ?>contact/">Contact Us</a>
            </li>
        </ul>
    </div>
</div>